# Generated by Django 4.2.6 on 2023-10-22 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Hero",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("alt_name", models.CharField(max_length=100)),
                ("primary_attribute", models.CharField(max_length=100)),
                ("image", models.ImageField(blank=True, upload_to="hero_images")),
            ],
            options={
                "verbose_name_plural": "Heroes",
                "ordering": ("primary_attribute", "name"),
            },
        ),
    ]
